web/appboard/urls.py
import os

from django.urls import path, re_path, include
from django.conf import settings
from . import views

app_name = "appboard"

urlpatterns = [
    path('', views.home, name='home'),
 
]

web/lms/urls.py
from django.urls import path, re_path
from lms import views
from django.conf import settings
from django.conf.urls.static import static
from project.models import Permission

app_name = 'lms'

PROJECT_BASE = '<str:slug>/'
OWNER_BASE = PROJECT_BASE + 'o/<str:owner>/'
PARCEL_BASE = PROJECT_BASE + 'p/<uuid:parcel>/'


urlpatterns = [
    path(PROJECT_BASE, views.lms_project, name='lms'),

    path(PROJECT_BASE + 'd', views.ProjectView.as_view(), name='project'),

    # Each view handles the myriad of post requests for each model. These views share very similar logic
    path(PROJECT_BASE + 'p', views.LMSParcelView.as_view(), name='parcels'),
    # path(PROJECT_BASE + 'p/<uuid:parcel>', views.ParcelView.as_view(), name='parcel'),
    path(PROJECT_BASE + 'p/<str:parcel>', views.LMSParcelView.as_view(), name='parcel'),
    path(PROJECT_BASE + 'p/<uuid:parcel>/modify', views.ParcelView.as_view(), name='modify_parcel'),

    path(PROJECT_BASE + 'p/<uuid:parcel>/map', views.MapView.as_view(), name='parcel_map'),

    path(PROJECT_BASE + 'h/<str:model>/<uuid:object>', views.HistoryView.as_view(), name='histories'),
    path(PROJECT_BASE + 'h/<str:model>/<uuid:object>/<uuid:history>', views.HistoryView.as_view(), name='history'),
    path(PROJECT_BASE + 'h/<str:model>/<uuid:object>/<uuid:history>/r', views.HistoryView.as_view(), name='revert_history'),

    # Handling owners is a bit tricky as there's stuff related to only a project or additionally a parcel relationship.
    path(PROJECT_BASE + 'o', views.OwnerView.as_view(), name='owners'),
    path(PROJECT_BASE + 'o/<uuid:owner>', views.OwnerView.as_view(), name='owner'),
    path(PROJECT_BASE + 'o/<uuid:owner>/modify', views.OwnerView.as_view(), name='modify_owner'),
    path(PROJECT_BASE + 'o/<uuid:owner>/delete', views.OwnerView.as_view(), name='delete_owner'),

    path(PARCEL_BASE + 'r', views.RelationshipView.as_view(), name='relationships'),
    path(PARCEL_BASE + 'r', views.RelationshipView.as_view(), name='relationships_new_owner'),
    path(PARCEL_BASE + 'r/<uuid:relationship>', views.RelationshipView.as_view(), name='relationship'),
    path(PARCEL_BASE + 'r/<uuid:relationship>/modify', views.RelationshipView.as_view(), name='modify_relationship'),
    path(PARCEL_BASE + 'r/<uuid:relationship>/delete', views.RelationshipView.as_view(), name='delete_relationship'),

    path(PARCEL_BASE + 'r/mail', views.MailView.as_view(), name='relationships_mail'),
    # This stuff is straight forward as it related only to the owner
    path(OWNER_BASE + 'n', views.NoteView.as_view(), name='notes'),
    path(OWNER_BASE + 'n/<uuid:note>', views.NoteView.as_view(), name='note'),
    path(OWNER_BASE + 'n/<uuid:note>/modify', views.NoteView.as_view(), name='modify_note'),
    path(OWNER_BASE + 'n/<uuid:note>/delete', views.NoteView.as_view(), name='delete_note'),

    path(OWNER_BASE + 't', views.TaskView.as_view(), name='tasks'),
    path(OWNER_BASE + 't/<uuid:task>', views.TaskView.as_view(), name='task'),
    path(OWNER_BASE + 't/<uuid:task>/modify', views.TaskView.as_view(), name='modify_task'),
    path(OWNER_BASE + 't/<uuid:task>/delete', views.TaskView.as_view(), name='delete_task'),

    path(OWNER_BASE + 'c', views.CorrespondenceView.as_view(), name='correspondences'),
    path(OWNER_BASE + 'c/<uuid:correspondence>', views.CorrespondenceView.as_view(), name='correspondence'),
    path(OWNER_BASE + 'c/<uuid:correspondence>/f/<uuid:file>/download', views.CorrespondenceView.as_view(), name='correspondence_download_file'),
    path(OWNER_BASE + 'c/<uuid:correspondence>/f/<uuid:file>/delete', views.CorrespondenceView.as_view(), name='correspondence_delete_file'),
    path(OWNER_BASE + 'c/<uuid:correspondence>/modify', views.CorrespondenceView.as_view(), name='modify_correspondence'),
    path(OWNER_BASE + 'c/<uuid:correspondence>/delete', views.CorrespondenceView.as_view(), name='delete_correspondence'),

    path(OWNER_BASE + 'r', views.ReminderView.as_view(), name='reminders'),
    path(OWNER_BASE + 'r/<uuid:reminder>', views.ReminderView.as_view(), name='reminder'),
    path(OWNER_BASE + 'r/<uuid:reminder>/modify', views.ReminderView.as_view(), name='modify_reminder'),
    path(OWNER_BASE + 'r/<uuid:reminder>/delete', views.ReminderView.as_view(), name='delete_reminder'),

    path(OWNER_BASE + 'f', views.FilesView.as_view(), name='files'),
    path(OWNER_BASE + 'f/<uuid:file>', views.FilesView.as_view(), name='file'),
    path(OWNER_BASE + 'f/<uuid:file>/download', views.FilesView.as_view(), name='download_file'),
    path(OWNER_BASE + 'f/<uuid:file>/delete', views.FilesView.as_view(), name='delete_file'),
]

if settings.DEBUG:
    urlpatterns += [

    ]

web/main/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static

from main import settings

if settings.DEBUG:
    from main.debug import views

urlpatterns = [
    # Django admin page
    path('admin/', admin.site.urls),

    # Main landing page
    path('', include('website.urls')),

    # App urls
    path('dashboard/', include('appboard.urls'), name='appboard'),
    path('geochem/', include('geochem.urls'), name='geochem'),
    path('project/', include('project.urls'), name='project'),
    path('lms/', include('lms.urls'), name='lms'),
    path('nms/', include('native_title_management.urls'), name='nms'),
    path('kms/', include('knowledge_management_system.urls'), name='kms'),
    path('tms/', include('tms.urls'), name='tms'),
    path('user/', include('user.urls'), name='user'),
    path('interactive_map/', include('interactive_map.urls'), name='interactive_map'),
    path('gis/', include('geodesk_gis.urls'), name='gis'),
    # path('search_engine/', include('search_engine.urls'), name='search_engine'),
    path('project_management/', include('project_management.urls'), name='project_management'),
    path('forms/', include('autoform.urls'), name='autoform'),
    path('media_file/', include('media_file.urls'), name='media_file'),

    path('notification/', include('notification.urls'), name='notification'),
    path('data_catalogue/', include('data_catalogue.urls'), name='data_catalogue'),
]

if settings.DEBUG:
    urlpatterns += [
        path('debug/', views.platform_debug_setup_view, name='debug_setup'),
        # path('testapi/', include('testapi.urls'), name='testapi')
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/project/urls.py
from django.urls import path

from interactive_map.views import main as im_main
from . import views
from .utils import post

app_name = 'project'

PROJECT_BASE = 'p/<str:slug>/'

urlpatterns = [
    path('', views.project_index, name='index'),
    # path('new_project/', views.render_region_form, name='render-region-form'),
    path('new_project/', views.new_project, name='new_project'),
    path('get_states/', views.get_states, name='get_states'),

    path('my_projects/', views.my_projects, name='my_projects'),
    path('my_tenements/', views.my_tenements, name='my_tenements'),
    path('project_kms/', views.project_kms_view, name='project_kms'),
    path('project_lms/', views.project_lms_view, name='project_lms'),

    # path('create_project/', views.new_project, name='new_project'),
    # GET Requests
    # Project Index
    path('get/projects/', views.get_projects, name='get_projects'),
    path('get/tenements/', views.get_tenements, name='get_tenements'),
    path('get/tenements/', views.get_reports, name='get_reports'),

    path('post/create/', post.create_project, name='create_project'),

    # Project Dashboard
    path(PROJECT_BASE, views.project_dashboard, name='dashboard'),
    path(PROJECT_BASE + 'get/tenements/', views.get_project_tenements, name='get_project_tenements'),
    path(PROJECT_BASE + 'get/targets/', views.get_targets, name='get_targets'),
    path(PROJECT_BASE + 'get/tasks/', views.get_tasks, name='get_tasks'),
    path(PROJECT_BASE + 'get/members/', views.get_members, name='get_members'),
    path(PROJECT_BASE + 'get/datasets/', views.get_datasets, name='get_datasets'),
    path(PROJECT_BASE + 'get/models/', views.get_models, name='get_models'),
    path(PROJECT_BASE + 'get/reports/', views.get_reports, name='get_reports'),

    path(PROJECT_BASE + 'get/file/<str:uuid>', views.project_file_download, name='get_file'),

    # Project Map Views
    path(PROJECT_BASE + 'get/project_map/', views.get_project_map, name='get_project_map'),
    # path(PROJECT_BASE + 'get/tenements_json/', im_views.get_multi_tenements_json, name='get_tenements_json'),
    # path(PROJECT_BASE + 'get/tenements_geojson/', im_views.get_tenements_geojson, name='get_tenements_geojson'),
    
    # POST Requests
    path(PROJECT_BASE + 'post/delete/', post.delete_project, name='delete_project'),
    path(PROJECT_BASE + 'post/leave/', post.leave_project, name='leave_project'),

    path(PROJECT_BASE + 'post/tenement/add/', post.add_tenement, name='add_tenement'),

    path(PROJECT_BASE + 'post/target/add/', post.add_target, name='add_target'),
    path(PROJECT_BASE + 'post/target/edit/<str:target_name>', post.edit_target, name='edit_target'),
    path(PROJECT_BASE + 'post/target/delete/', post.delete_target, name='delete_target'),

    path(PROJECT_BASE + 'post/task/add/', post.add_task, name='task_add'),
    path(PROJECT_BASE + 'post/task/delete/', post.delete_task, name='task_delete'),

    path(PROJECT_BASE + 'post/member/invite/', post.invite_member, name='member_invite'),
    path(PROJECT_BASE + 'post/member/delete/', post.delete_member, name='member_delete'),

    path(PROJECT_BASE + 'post/dataset/add/', post.add_dataset, name='dataset_add'),
    path(PROJECT_BASE + 'post/dataset/delete/', post.delete_file, name='dataset_delete'),

    path(PROJECT_BASE + 'post/model/add/', post.add_model, name='model_add'),
    path(PROJECT_BASE + 'post/model/delete/', post.delete_file, name='model_delete'),

    path(PROJECT_BASE + 'post/report/delete/', post.delete_file, name='report_delete'),
]

web/user/urls.py
import os

from django.urls import path, re_path, include
from django.conf import settings
from django.contrib.auth import views as auth_views
from . import views

app_name = "user"

urlpatterns = [
    path('', views.home, name='home'),

    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='user:login'), name='logout'),
    path('change_password/', auth_views.PasswordChangeView.as_view(template_name='user/changepassword.html'), name='change_password'),
    path('email/', views.email_view, name='email'),
    path('inactive/', views.inactive_view, name='inactive'),
    path('check_username/', views.check_username, name='check_username'),
    path("password_reset/", views.password_reset_request, name="password_reset"),
    path('reset/<uidb64>/<token>/', views.passwordResetConfirm, name='password_reset_confirm'),
	path('manage/',views.manage_account_view, name='manage',),

]

web/website/urls.py
from django.urls import path
from . import views

app_name = 'website'

urlpatterns = [
    path('', views.website_home, name='home'),
    path('message/', views.contact_message, name='contact_message'),
]

web/notification/models.py
import uuid
from itertools import chain

from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.core import serializers
from django.core.serializers import serialize
from django.core.serializers.json import DjangoJSONEncoder
from django.db import models
from django.contrib.auth import get_user_model
from django.db.models import CheckConstraint, Q
from django.forms import model_to_dict

from project.models import Project

User = get_user_model()


class Notification(models.Model):
    """A generic notification model."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    # Notification information, who did it and what did they do?
    user_from = models.ForeignKey(User, on_delete=models.CASCADE)
    summary = models.CharField(max_length=256)
    url = models.CharField(max_length=100, null=True, blank=True)  # If we need to route to a specific location

    # The target is basically the object in which the notification is for. For example, if a user modifies a project
    # the project would be the target.
    target_type = models.ForeignKey(ContentType, on_delete=models.SET_NULL, null=True, blank=True)
    target_id = models.CharField(max_length=36, null=True, blank=True)
    target = GenericForeignKey('target_type', 'target_id')

    timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-timestamp']

    def create_status_for_users(self, **user_query_dict):
        """Creates a NotificationStatus for every user in the user_query_dict"""
        queryset = User.objects.filter(**user_query_dict).exclude(user=self.user_from).all()

        for user in queryset:
            self.status.create(user=user)


class NotificationStatus(models.Model):
    """Relational model for storing user specific information regarding the Notification. e.g., Has the user read
    the notification.
    """
    # TODO: Add this again when the frontend can sort by the timestamp field
    # id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    notification = models.ForeignKey(Notification, on_delete=models.CASCADE, related_name='status')
    is_read = models.BooleanField(default=False)

    class Meta:
        unique_together = ['user', 'notification']
        ordering = ['-notification__timestamp']

web/website/models.py
import uuid

from django.contrib.auth import get_user_model
from django.contrib.auth.models import Permission
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.contrib.postgres.fields import ArrayField
from django.core.exceptions import ObjectDoesNotExist, ValidationError
from django.db import models


User = get_user_model()


class ContactMessage(models.Model):
    """
    Models for contact message 
    """
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=50)
    subject = models.CharField(max_length=256)
    body = models.TextField(max_length=5000)

    def __str__(self):
        return self.subject

web/website/forms.py
from django import forms
from .models import Contact

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ('name', 'email', 'phone', 'message')
    
    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'
            visible.field.widget.attrs['placeholder'] = visible.label

web/notification/views.py
from http import HTTPStatus

from django.contrib.auth import login, get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.views import View


# Create your views here.
User = get_user_model()


class IndexView(LoginRequiredMixin, View):
    template = 'notification/index.html'

    def get(self, request, *args, **kwargs):
        context = {}
        return render(request, self.template, context)

    def post(self, request, *args, **kwargs):
        context = {}
        return render(request, self.template, context)


class RoomView(LoginRequiredMixin, View):
    template = 'notification/rooms.html'

    def get(self, request, *args, **kwargs):
        context = {}
        return render(request, self.template, context)

    def post(self, request, *args, **kwargs):
        context = {}
        return render(request, self.template, context)


class ToggleView(LoginRequiredMixin, View):

    def get(self, request, *args, **kwargs):

        email = {
            'admin@email.com': 'user1@email.com',
            'user1@email.com': 'user2@email.com',
            'user2@email.com': 'user3@email.com',
            'user3@email.com': 'admin@email.com',
        }.get(request.user.email)

        user = User.objects.get(email=email)
        login(request, user)

        return redirect('notification:index')

web/website/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.views import View

import os
from . import models


def website_home(request):
    if request.user.is_authenticated:
        return redirect('appboard:home')

    template_name = 'website/home.html'
    context = {}
    return render(request, template_name, context=context)


def contact_message(request):
    if request.method == "POST":
        data = request.POST
        models.ContactMessage.objects.create(
            name=data['name'],
            email=data['email'],
            subject=data['subject'],
            body=data['body']
        )
        messages.success(request, 'Your message has been sent! Thank You')
        return redirect('website:home')

    messages.error(request, 'Something wrong happened!')
    return redirect('website:home')

web/website/templates/website/contact.html
{% extends "website/base.html" %}
{% load static %}

{% block content %}




<!-- breadcrumb-area start -->
<div class="breadcrumb-area bg-img" data-bg="{% static 'website/images/bg/breadcrumb_bg.jpg' %}">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="breadcrumb_box text-center">
                    <h2 class="breadcrumb-title title--default">Contact_</h2>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- breadcrumb-area end -->


<!--============ Personal Contact Us Area Start ============-->
<div class="personal-contact-us-area section-space--pt_120 section-space--pb_60">
    <div class="container">
        <div class="row">
            <div class="col-lg-5">
                <div class="contact-us-info section-space--mb_40">
                    <div class="section-title-wrap">
                        <h6 class="section-sub-title">Contact</h6>
                        <h4 class="mb-20 theme-color-default">Hello, what’s on your mind?</h4>
                        <p class="mb-15 font-weight--light">Most popular typesetting, remaining are essentially was popu
                            larised in the 1960s with the release of uncov er many web sites
                            in their infancy. Various are versions have evolved</p>
                    </div>

                    <div class="contact-widget__wrap section-space--mt_50">
                        <div class="single-footer-widger mb-30">
                            <h5 class="mb-10">Address</h5>
                            <p>275 South Poal, 4th Floor Central Plaza, Main Town, New Yourk, USA</p>
                        </div>
                        <div class="single-footer-widger mb-30">
                            <h5 class="mb-10">Phone</h5>
                            <p>01254 879 658, 65987 456 987 <br> 01256 879 857, 0123456789</p>
                        </div>
                        <div class="single-footer-widger mb-30">
                            <h5 class="mb-10">Web</h5>
                            <p>
                                <a href="#">info@example.com</a> <br>
                                <a href="#">www.example.com</a>
                            </p>
                        </div>

                        <div class="social-share">
                            <h5 class="mb-10 personal-share-title">Also find me here</h5>
                            <ul class="list ht-social-networks default-color">

                                <li class="item">
                                    <a href="https://facebook.com" target="_blank">
                                        <i class="fa fa-facebook-f link-icon"></i>
                                    </a>
                                </li>
                                <li class="item">
                                    <a href="https://twitter.com" target="_blank">
                                        <i class="fa fa-twitter link-icon"></i>
                                    </a>
                                </li>
                                <li class="item">
                                    <a href="https://instagram.com" target="_blank">
                                        <i class="fa fa-instagram link-icon"></i>
                                    </a>
                                </li>
                                <li class="item">
                                    <a href="https://linkedin.com" target="_blank">
                                        <i class="fa fa-linkedin link-icon"></i>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>


                </div>
            </div>
            <div class="col-lg-7">
                <div class="contact-us-form section-space--mb_40">
                    <form  action="{% url 'website:contact' %}" method="POST"> <!--id="contact-form"-->
                        {% csrf_token %}
                        <div class="contact-form__one ml-lg-5">

                            <div class="contact-title section-space--mb_30">
                                <h4 class="text-white">Send us a message</h4>
                            </div>

                            <div class="contact-input input-row">
                                <div class="contact-inner input-col-5">
                                    <input name="name" type="text" placeholder="Name *" required>
                                </div>
                                <div class="contact-inner input-col-5">
                                    <input name="email" type="email" placeholder="Email *" required>
                                </div>
                            </div>
                            
                            <div class="contact-input">
                                <div class="contact-inner">
                                    <input name="subject" type="text" placeholder="Subject *" required>
                                </div>
                            </div>
                            <div class="contact-inner contact-message">
                                <textarea name="message" placeholder="Message*" required></textarea>
                            </div>
                            <div class="comment-submit-btn text-right">
                                <button class="ht-btn ht-btn-sm personal-contact-btn" type="submit">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<!--============ Personal Contact Us Area End ============-->




{% endblock %}

web/website/templates/website/header_top.html
<div class="header-top-wrap theme-bg-three">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="header default-menu-style position-relative">
                    <div class="header-midle-box">
                        <div class="header-bottom-wrap d-md-block">
                            <div class="navigation-menu top-message text-right">
                                {% if request.user.is_authenticated %}
                                    <li class="has-child">
                                        <a class="dropdown-toggle" href="#">{{request.user.email}}</a>
                                        <ul class="submenu submenu-right">
                                            <li><a href="{% url 'appboard:home' %}"><span>Dashboard</span></a></li>
                                            <li><a href="{% url 'user:inactive' %}"><span>Status</span></a></li>
                                            <li><a href="{% url 'user:email' %}"><span>My Emails</span></a></li>
                                            <li><a href="{% url 'user:change_password' %}"><span>Change Pass</span></a></li>
                                            <li><a href="{% url 'user:logout' %}"><span>Logout</span></a></li>
                                        </ul>
                                    </li>
                                {% else %}
                                    <li>
                                        <a href="{% url 'user:login' %}">Login</a> <span class="text-white"> / </span> <a href="{% url 'user:register' %}">Register</a>
                                    </li>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
                
            </div>
        </div>
    </div>
</div>

web/website/templates/website/menu.html
<ul>
    <li class="has-children active">
        <a href="#home"><span>Home</span></a>
    </li>
    <li class="has-children">
        <a href="#about"><span>About</span></a>
    </li>
    <li class="has-children">
        <a href="#process"><span>Process</span></a>
    </li>
    <li class="has-children">
        <a href="#solutions"><span>Solutions</span></a>
    </li>
    <li class="has-children">
        <a href="#testimonial"><span>Testimonial</span></a>
    </li>
    <li class="has-children">
        <a href="#contact"><span>Contact</span></a>
    </li>
</ul>

web/website/templates/website/notification.html
<div class="" id="message_container" style="position: fixed; z-index: 99998; width: 100%;">
    <div class="container m-auto">
        
        <!-----------  Anouncement --------------->
        <!-----------  Anouncement Ends --------------->

        <!-------------- Message Area ----------------->
        {% if messages %}
        {% for message in messages %}
        <div class="web-alert alert {{ message.tags }} alert-base alert-dismissible fade show m-2 shadow" role="alert">
            {{message|safe}}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endfor %}
        {% endif %}
        <!-------------- Message Area Ends ----------------->

    </div>
</div>

web/website/templates/website/preloader.html
<div class="preloader-activate preloader-active open_tm_preloader">
    <div class="preloader-area-wrap">
        <div class="spinner d-flex justify-content-center align-items-center h-100">
            <div class="bounce1"></div>
            <div class="bounce2"></div>
            <div class="bounce3"></div>
        </div>
    </div>
</div>