web/lms/urls.py
from django.urls import path, re_path
from lms import views
from django.conf import settings
from django.conf.urls.static import static
from project.models import Permission

app_name = 'lms'

PROJECT_BASE = '<str:slug>/'
OWNER_BASE = PROJECT_BASE + 'o/<str:owner>/'
PARCEL_BASE = PROJECT_BASE + 'p/<uuid:parcel>/'


urlpatterns = [
    path(PROJECT_BASE, views.lms_project, name='lms'),

    path(PROJECT_BASE + 'd', views.ProjectView.as_view(), name='project'),

    # Each view handles the myriad of post requests for each model. These views share very similar logic
    path(PROJECT_BASE + 'p', views.LMSParcelView.as_view(), name='parcels'),
    # path(PROJECT_BASE + 'p/<uuid:parcel>', views.ParcelView.as_view(), name='parcel'),
    path(PROJECT_BASE + 'p/<str:parcel>', views.LMSParcelView.as_view(), name='parcel'),
    path(PROJECT_BASE + 'p/<uuid:parcel>/modify', views.ParcelView.as_view(), name='modify_parcel'),

    path(PROJECT_BASE + 'p/<uuid:parcel>/map', views.MapView.as_view(), name='parcel_map'),

    path(PROJECT_BASE + 'h/<str:model>/<uuid:object>', views.HistoryView.as_view(), name='histories'),
    path(PROJECT_BASE + 'h/<str:model>/<uuid:object>/<uuid:history>', views.HistoryView.as_view(), name='history'),
    path(PROJECT_BASE + 'h/<str:model>/<uuid:object>/<uuid:history>/r', views.HistoryView.as_view(), name='revert_history'),

    # Handling owners is a bit tricky as there's stuff related to only a project or additionally a parcel relationship.
    path(PROJECT_BASE + 'o', views.OwnerView.as_view(), name='owners'),
    path(PROJECT_BASE + 'o/<uuid:owner>', views.OwnerView.as_view(), name='owner'),
    path(PROJECT_BASE + 'o/<uuid:owner>/modify', views.OwnerView.as_view(), name='modify_owner'),
    path(PROJECT_BASE + 'o/<uuid:owner>/delete', views.OwnerView.as_view(), name='delete_owner'),

    path(PARCEL_BASE + 'r', views.RelationshipView.as_view(), name='relationships'),
    path(PARCEL_BASE + 'r', views.RelationshipView.as_view(), name='relationships_new_owner'),
    path(PARCEL_BASE + 'r/<uuid:relationship>', views.RelationshipView.as_view(), name='relationship'),
    path(PARCEL_BASE + 'r/<uuid:relationship>/modify', views.RelationshipView.as_view(), name='modify_relationship'),
    path(PARCEL_BASE + 'r/<uuid:relationship>/delete', views.RelationshipView.as_view(), name='delete_relationship'),

    path(PARCEL_BASE + 'r/mail', views.MailView.as_view(), name='relationships_mail'),
    # This stuff is straight forward as it related only to the owner
    path(OWNER_BASE + 'n', views.NoteView.as_view(), name='notes'),
    path(OWNER_BASE + 'n/<uuid:note>', views.NoteView.as_view(), name='note'),
    path(OWNER_BASE + 'n/<uuid:note>/modify', views.NoteView.as_view(), name='modify_note'),
    path(OWNER_BASE + 'n/<uuid:note>/delete', views.NoteView.as_view(), name='delete_note'),

    path(OWNER_BASE + 't', views.TaskView.as_view(), name='tasks'),
    path(OWNER_BASE + 't/<uuid:task>', views.TaskView.as_view(), name='task'),
    path(OWNER_BASE + 't/<uuid:task>/modify', views.TaskView.as_view(), name='modify_task'),
    path(OWNER_BASE + 't/<uuid:task>/delete', views.TaskView.as_view(), name='delete_task'),

    path(OWNER_BASE + 'c', views.CorrespondenceView.as_view(), name='correspondences'),
    path(OWNER_BASE + 'c/<uuid:correspondence>', views.CorrespondenceView.as_view(), name='correspondence'),
    path(OWNER_BASE + 'c/<uuid:correspondence>/f/<uuid:file>/download', views.CorrespondenceView.as_view(), name='correspondence_download_file'),
    path(OWNER_BASE + 'c/<uuid:correspondence>/f/<uuid:file>/delete', views.CorrespondenceView.as_view(), name='correspondence_delete_file'),
    path(OWNER_BASE + 'c/<uuid:correspondence>/modify', views.CorrespondenceView.as_view(), name='modify_correspondence'),
    path(OWNER_BASE + 'c/<uuid:correspondence>/delete', views.CorrespondenceView.as_view(), name='delete_correspondence'),

    path(OWNER_BASE + 'r', views.ReminderView.as_view(), name='reminders'),
    path(OWNER_BASE + 'r/<uuid:reminder>', views.ReminderView.as_view(), name='reminder'),
    path(OWNER_BASE + 'r/<uuid:reminder>/modify', views.ReminderView.as_view(), name='modify_reminder'),
    path(OWNER_BASE + 'r/<uuid:reminder>/delete', views.ReminderView.as_view(), name='delete_reminder'),

    path(OWNER_BASE + 'f', views.FilesView.as_view(), name='files'),
    path(OWNER_BASE + 'f/<uuid:file>', views.FilesView.as_view(), name='file'),
    path(OWNER_BASE + 'f/<uuid:file>/download', views.FilesView.as_view(), name='download_file'),
    path(OWNER_BASE + 'f/<uuid:file>/delete', views.FilesView.as_view(), name='delete_file'),
]

if settings.DEBUG:
    urlpatterns += [

    ]

web/main/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static

from main import settings

if settings.DEBUG:
    from main.debug import views

urlpatterns = [
    # Django admin page
    path('admin/', admin.site.urls),

    # Main landing page
    path('', include('website.urls')),

    # App urls
    path('dashboard/', include('appboard.urls'), name='appboard'),
    path('geochem/', include('geochem.urls'), name='geochem'),
    path('project/', include('project.urls'), name='project'),
    path('lms/', include('lms.urls'), name='lms'),
    path('nms/', include('native_title_management.urls'), name='nms'),
    path('kms/', include('knowledge_management_system.urls'), name='kms'),
    path('tms/', include('tms.urls'), name='tms'),
    path('user/', include('user.urls'), name='user'),
    path('interactive_map/', include('interactive_map.urls'), name='interactive_map'),
    path('gis/', include('geodesk_gis.urls'), name='gis'),
    # path('search_engine/', include('search_engine.urls'), name='search_engine'),
    path('project_management/', include('project_management.urls'), name='project_management'),
    path('forms/', include('autoform.urls'), name='autoform'),
    path('media_file/', include('media_file.urls'), name='media_file'),

    path('notification/', include('notification.urls'), name='notification'),
    path('data_catalogue/', include('data_catalogue.urls'), name='data_catalogue'),
]

if settings.DEBUG:
    urlpatterns += [
        path('debug/', views.platform_debug_setup_view, name='debug_setup'),
        # path('testapi/', include('testapi.urls'), name='testapi')
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/project/urls.py
from django.urls import path

from interactive_map.views import main as im_main
from . import views
from .utils import post

app_name = 'project'

PROJECT_BASE = 'p/<str:slug>/'

urlpatterns = [
    path('', views.project_index, name='index'),
    # path('new_project/', views.render_region_form, name='render-region-form'),
    path('new_project/', views.new_project, name='new_project'),
    path('get_states/', views.get_states, name='get_states'),

    path('my_projects/', views.my_projects, name='my_projects'),
    path('my_tenements/', views.my_tenements, name='my_tenements'),
    path('project_kms/', views.project_kms_view, name='project_kms'),
    path('project_lms/', views.project_lms_view, name='project_lms'),

    # path('create_project/', views.new_project, name='new_project'),
    # GET Requests
    # Project Index
    path('get/projects/', views.get_projects, name='get_projects'),
    path('get/tenements/', views.get_tenements, name='get_tenements'),
    path('get/tenements/', views.get_reports, name='get_reports'),

    path('post/create/', post.create_project, name='create_project'),

    # Project Dashboard
    path(PROJECT_BASE, views.project_dashboard, name='dashboard'),
    path(PROJECT_BASE + 'get/tenements/', views.get_project_tenements, name='get_project_tenements'),
    path(PROJECT_BASE + 'get/targets/', views.get_targets, name='get_targets'),
    path(PROJECT_BASE + 'get/tasks/', views.get_tasks, name='get_tasks'),
    path(PROJECT_BASE + 'get/members/', views.get_members, name='get_members'),
    path(PROJECT_BASE + 'get/datasets/', views.get_datasets, name='get_datasets'),
    path(PROJECT_BASE + 'get/models/', views.get_models, name='get_models'),
    path(PROJECT_BASE + 'get/reports/', views.get_reports, name='get_reports'),

    path(PROJECT_BASE + 'get/file/<str:uuid>', views.project_file_download, name='get_file'),

    # Project Map Views
    path(PROJECT_BASE + 'get/project_map/', views.get_project_map, name='get_project_map'),
    # path(PROJECT_BASE + 'get/tenements_json/', im_views.get_multi_tenements_json, name='get_tenements_json'),
    # path(PROJECT_BASE + 'get/tenements_geojson/', im_views.get_tenements_geojson, name='get_tenements_geojson'),
    
    # POST Requests
    path(PROJECT_BASE + 'post/delete/', post.delete_project, name='delete_project'),
    path(PROJECT_BASE + 'post/leave/', post.leave_project, name='leave_project'),

    path(PROJECT_BASE + 'post/tenement/add/', post.add_tenement, name='add_tenement'),

    path(PROJECT_BASE + 'post/target/add/', post.add_target, name='add_target'),
    path(PROJECT_BASE + 'post/target/edit/<str:target_name>', post.edit_target, name='edit_target'),
    path(PROJECT_BASE + 'post/target/delete/', post.delete_target, name='delete_target'),

    path(PROJECT_BASE + 'post/task/add/', post.add_task, name='task_add'),
    path(PROJECT_BASE + 'post/task/delete/', post.delete_task, name='task_delete'),

    path(PROJECT_BASE + 'post/member/invite/', post.invite_member, name='member_invite'),
    path(PROJECT_BASE + 'post/member/delete/', post.delete_member, name='member_delete'),

    path(PROJECT_BASE + 'post/dataset/add/', post.add_dataset, name='dataset_add'),
    path(PROJECT_BASE + 'post/dataset/delete/', post.delete_file, name='dataset_delete'),

    path(PROJECT_BASE + 'post/model/add/', post.add_model, name='model_add'),
    path(PROJECT_BASE + 'post/model/delete/', post.delete_file, name='model_delete'),

    path(PROJECT_BASE + 'post/report/delete/', post.delete_file, name='report_delete'),
]

web/user/urls.py
import os

from django.urls import path, re_path, include
from django.conf import settings
from django.contrib.auth import views as auth_views
from . import views

app_name = "user"

urlpatterns = [
    path('', views.home, name='home'),

    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='user:login'), name='logout'),
    path('change_password/', auth_views.PasswordChangeView.as_view(template_name='user/changepassword.html'), name='change_password'),
    path('email/', views.email_view, name='email'),
    path('inactive/', views.inactive_view, name='inactive'),
    path('check_username/', views.check_username, name='check_username'),
    path("password_reset/", views.password_reset_request, name="password_reset"),
    path('reset/<uidb64>/<token>/', views.passwordResetConfirm, name='password_reset_confirm'),
	path('manage/',views.manage_account_view, name='manage',),

]

web/website/urls.py
from django.urls import path
from . import views

app_name = 'website'

urlpatterns = [
    path('', views.website_home, name='home'),
    path('message/', views.contact_message, name='contact_message'),
]

web/user/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.utils import timezone
import django.core.validators as validators
from django.utils.translation import gettext_lazy as _
from .managers import UserManager


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(_('email address'), unique=True)
    username = models.CharField(max_length=10, default="default", null=True, blank=True)
    first_name = models.CharField(max_length=32, default="Joe")
    last_name = models.CharField(max_length=32, default="Blogs")
    company = models.CharField(max_length=50, default="Orefox")
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(default=timezone.now)
    credits = models.DecimalField(default=0.0, decimal_places=2, max_digits=65,
                                  validators=[validators.MinValueValidator(0.0)])
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()

    @property
    def full_name(self):
        return f"{self.first_name} {self.last_name}"

    def __str__(self):
        return self.full_name

    def natural_key(self):
        return (self.email, self.username)

web/user/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
# from allauth.account import forms as allauth_forms
from django import forms as dj_forms
from django.utils.translation import gettext as _
from django.db import models
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from .models import User
from django.contrib.auth import authenticate
from django.contrib.auth.forms import AuthenticationForm

from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.forms import UserCreationForm
from django.core.validators import validate_email

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import SetPasswordForm, PasswordResetForm
from django.core.exceptions import ValidationError


# class RegistrationForm(UserCreationForm):
#    """
#    User Registration Form, extends django-auth form
#    """
#
#    class Meta:
#        model = User
#        fields = ('email', 'first_name', 'last_name', 'password1', 'password2', )

# class UserChangeForm(UserChangeForm):

#     class Meta:
#         model = User
#         fields = ('email',)


# class LoginForm(allauth_forms.LoginForm):
#     def __init__(self, *args, **kwargs):
#         super().__init__(*args, **kwargs)
#         for field_name, field in self.fields.items():
#             field.widget.attrs['class'] = 'form-control'


# class SignupForm(allauth_forms.SignupForm):
#     first_name = dj_forms.CharField(
#         label=_("First Name"),
#         widget=dj_forms.TextInput(
#             attrs={"placeholder": _("First Name"), "autocomplete": "first_name"}
#         )
#     )
#     last_name = dj_forms.CharField(
#         label=_("Last Name"),
#         widget=dj_forms.TextInput(
#             attrs={"placeholder": _("Last Name"), "autocomplete": "last_name"}
#         )
#     )


class RegistrationForm(UserCreationForm):
    first_name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'First Name', 'autocomplete': "off", }))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Last Name'}))
    company = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Company'}))

    email = forms.EmailField(widget=forms.EmailInput(
        attrs={'class': 'form-control', 'placeholder': 'Email', 'autocomplete': "off", 'autofocus': False}))
    password1 = forms.CharField(widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'placeholder': 'Password', 'autocomplete': "off", 'autofocus': False}))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'company', 'password1', 'password2')


class LoginForm(AuthenticationForm):
    username = forms.EmailField(widget=forms.EmailInput())

    error_messages = {
        'invalid_login': 'Invalid Email or Password',
        'inactive': 'This account is inactive.',
    }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password'].widget.attrs.update({'autocomplete': 'current-password'})

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if username and password:
            self.user_cache = authenticate(email=username, password=password)
            if self.user_cache is None:
                raise self.get_invalid_login_error()
            else:
                self.confirm_login_allowed(self.user_cache)

        return self.cleaned_data

    def get_invalid_login_error(self):
        return ValidationError(
            self.error_messages['invalid_login'],
            code='invalid_login',
            params={'username': self.username_field.verbose_name},
        )


class SetPasswordForm(SetPasswordForm):
    class Meta:
        model = User
        fields = ['new_password1', 'new_password2']


class PasswordResetForm(PasswordResetForm):
    def __init__(self, *args, **kwargs):
        super(PasswordResetForm, self).__init__(*args, **kwargs)    

web/user/templates/user/password_reset.html
{% extends "base.html" %}
{% load i18n static %}
{% load static %}
{% block content %}
<section class="gradient-form" style="background-color: #fff;height:98%; width:99%">
       <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-md-6 d-flex align-items-center gradient-custom-2 h-100" id="start-sidebar">
            <div class="text-white px-3 py-2 p-md-5 mx-md-4">
              <h4 class="mb-2">We’re GeoDesk AI</h4>
              <p class="small mb-5">
                We provide artificial intelligence-based geological data analytics to
                mining and exploration companies.
              </p>
              <h4 class="mb-2 mt-5">GeoDesk AI</h4>
              <p class="small mb-0">
                GeoDesk AI is a platform that can bring more efficiency to mineral
                exploration. It can store and analyse the majority of geological data used
                in exploration, using traditional, cutting-edge methods.
              </p>
            </div>
          
          </div>
            <div class="col-md-6 h-100">
                <div class="" style=" position:absolute; float:right;top:20px; right:20px ">
                    <a href="{% url 'website:home' %}">
                    <img
                    class="img-profile"
                    style="height: 25px; width: 120px; "
                    src="{% static '.\user\img\orefox-logo.png' %}"
                    alt=""
                  /> 
                  
              
                    </a>
                  </div>
                <div class="card-body w-100 row d-flex align-items-center justify-content-center" style="margin-top:160px" >
  
                
                  
                  <form method="post" class="col-xl-6 col-8" >
                    {% csrf_token %}
                    {% if messages %}
                    <div id="flash-message" class="alert alert-danger text-md p-3" style="position:absolute;top:110px;width:23%">
                        {% for message in messages %}
                            {{ message }}
                        {% endfor %}
                    </div>
                {% endif %}
                    {% if form.errors %}
                    <div class="alert alert-danger pt-0 pb-0 mt-0">
                      {% for field, errors in form.errors.items %}
                      {% for error in errors %}
                      <span style="font-size : .70rem"> {{ error }}<br></span>
                      {% endfor %}
                      {% endfor %}
                    </div>
                    {% endif %}
                    <h4 class="text-center mb-5">Forgot Password</h4>
                    <div class="form-outline mb-4 mt-2">
                      <input type="email" name="email" id="id_email" class="form-control"
                        placeholder="Email address" />
                      <label class="form-label" for="id_email">Email</label>
                    </div>
  
                    
  
                    <div class="text-center pt-1 mb-5 pb-1">
                      <button class="btn btn-primary btn-block fa-lg gradient-custom-2 mb-3" 
                      id="send-email-btn" type="submit" disabled>Send Email</button>
                      <a class="text-muted" href="{% url 'user:login' %}">Sign In</a>
                    </div>
  
                    <div class="d-flex align-items-center justify-content-center pb-4">
                      <p class="mb-0 me-2">Don't have an account?</p>
                      <a type="submit" class="btn btn-outline-danger" href="{% url 'user:register' %}">
                        Sign Up</a>
                    </div>
  
                  </form>
  
                </div>
              </div>
            
      
    </div>
  </section>
  <script>
    const emailInput = document.querySelector('#id_email');
     const sendEmailButton = document.querySelector('#send-email-btn');
  
    emailInput.addEventListener('input', () => {
        sendEmailButton.disabled = !(emailInput.value);
    });
  
    setTimeout(function () {
      if( document.getElementById("flash-message") !== null)
      document.getElementById("flash-message").style.display = "none";
    }, 3000); 
  </script>
{% endblock %}

web/user/templates/user/register.html
{% extends "base.html" %} {% load i18n static %} {% load static %} 
{% block content %}

<section
  class="gradient-form"
  style="background-color: #fff; height: 98%; width: 99%"
>
  <div class="row d-flex justify-content-center align-items-center h-100">
    <div
      class="col-md-6 d-flex gradient-custom-2 h-100"
      id="start-sidebar"
    >
    
      <div>
        <a href="{% url 'website:home' %}">
          <img
            class="img-profile"
            style="object-fit: contain; margin-left: 1rem; margin-top: 1rem; object-position: top; width: 25%; height: 25%;"
            src="{% static 'website/images/logo/GeoDesk.Ai_logo-with_text.png' %}"
            alt=""
          />
        </a>

        <div class="text-white px-3 py-2 p-md-5 mx-md-4">

          <h4 class="mb-2">Instant Access to Your Exploration Management</h4>
          <p class="small mb-5">
            Register now for immediate, free access to manage your exploration projects efficiently. No paywalls, no waiting - just enter your tenement ID, and GeoDesk.Ai instantly provides the tools and insights you need to propel your exploration forward.
          </p>

          <!-- <h4 class="mb-2">We’re GeoDesk AI</h4>
          <p class="small mb-5">
            We provide artificial intelligence-based geological data analytics to
            mining and exploration companies.
          </p>
          <h4 class="mb-2 mt-5">GeoDesk AI</h4>
          <p class="small mb-0">
            GeoDesk AI is a platform that can bring more efficiency to mineral
            exploration. It can store and analyse the majority of geological data used
            in exploration, using traditional, cutting-edge methods.
          </p> -->
        </div>

      </div>
    
    </div>
    <div class="col-md-6 h-100">
      
      <div
        class="card-body mx-auto row w-100 d-flex align-items-center justify-content-center"
        style="margin-top: 140px"
      >
      <div class="col-xl-6 col-8">
        <div id="flash-message" class="text-md ms-2 mb-2 position-relative">
          {% if messages %}
          {% for message in messages %} 
          {% if message.level == 40 %}
          <div
          class="alert alert-danger p-3">  {{ message }}
        </div>
          
          {% elif message.level == 25 %}
          <div
          class="alert alert-success p-3">{{ message }}
          </div>
          {% endif %}
          {% endfor %}
          {% elif form.errors %}
          <div
            class="alert alert-danger pt-0 pb-0 mt-0"
            >
            {% for field, errors in form.errors.items %} 
            {% for error in errors %}
            <span>f{{ error }}<br /></span>
            {% endfor %} {% endfor %}
          </div>
        
          
          {% endif %}
      </div>
    
        <form method="post" class="ms-4" id="register-form">
          {% csrf_token %} 
          <div class="row"  id="client-error" >
          <div class="col-12 text-start d-flex flex-column justify-content-end align-items-start p-0"
                      
          ></div>
          </div>
          <div class="row mt-3 mb-3">
            <div class="form-outline col-11 fw-bolder ps-0">
            {{form.account_type}} 
            </div>
          </div>
          <div class="row mt-3 mb-3">
            <div class="form-outline col-10">
               {{form.first_name}}
               <label class="form-label" for="id_first_name">First Name</label>
            </div>
           <div class="cross-marker col-1 text-start ms-1">
              <i class="fas fa-check fname-cross-marker"></i>
           </div>
        </div>
        <div class="row">
          <div class="form-outline mb-3 col-10">
            {{form.last_name}}
            <label class="form-label" for="id_last_name">Last Name</label>
          </div>
          <div class="cross-marker col-1 text-start ms-1" 
            ><i class="fas fa-check lname-cross-marker"></i
          ></div>
        </div>
          <div class="row">
            <div class="form-outline mb-3 col-10">
              {{form.email}} 
            <label class="form-label" for="id_email">Email</label>
          </div>
          <div class="cross-marker col-1 text-start ms-1" 
            ><i class="fas fa-check email-cross-marker"></i
          ></div>
        </div>
          <div class="row">
            <div class="form-outline mb-3 col-10">
            {{form.company}}
            <label class="form-label" for="id_company">Company</label>
          </div>
          <div class="cross-marker col-1 text-start ms-1" 
            ><i class="fas fa-check company-cross-marker"></i
          ></div>
        </div>

          <div class="row">
            <div class="form-outline mb-3 col-10">
            {{form.password1}}
            <label class="form-label" for="id_password1">Password</label>
            </div>
            <div class="cross-marker col-1 text-start ms-1" 
              ><i class="fas fa-check password1-cross-marker"></i
            ></div>
          </div>

          <ul id="password_requirements" style="display: none;">
            <li class="error" id="pass_length">
              8 to 24 Characters
            </li>
            <li class="error" id="pass_upper">
              At least one uppercase
            </li>
            <li class="error" id="pass_number">
              At least one digit
            </li>
            <li class="error" id="pass_special">
              At least one special character
            </li>
          </ul>

          <div class="row">
            <div class="form-outline mb-3 col-10">
            <input
              type="password"
              name="password2"
              id="id_password2"
              class="form-control"
            />
            <label class="form-label" for="id_password2"
              >Confirm Password</label
            >
          </div>
          <div class="cross-marker col-1 text-start ms-1" 
            ><i class="fas fa-check password2-cross-marker"></i
          ></div>
        </div>
        <div class="form-check" style="font-size:12px;" id="terms_conditions">
          <input class="form-check-input" type="checkbox" id="acceptTerms" name="acceptTerms" required>
          <label class="form-check-label" for="acceptTerms">
              I accept the <a href="#" data-bs-toggle="modal" data-bs-target="#termsModal">Terms and Conditions</a>
          </label>
      </div>
          <div class=" row mb-3">
            <button
              class="btn btn-primary col-10 fa-lg gradient-custom-2  ms-0"
              id="register-btn"
              type="submit"
              disabled           

            >
              Sign Up
            </button>
            <div class="text-danger text-sm">**All fields are mandatory</div>
          </div>

         
          <div class="row text-start">
            <div class="col-11">
            <span class="mb-0">Already have an account?</span>
            <a
              type="button"
              class="btn btn-outline-danger px-3"
              href="{% url 'user:login' %}"
            >
              Sign In</a
            ></div>
          </div>
        </form>
      </div>
    </div>
  </div>
</section>
<!-- Terms and Conditions Modal -->
<div class="modal fade" id="termsModal" tabindex="-1" role="dialog" aria-labelledby="termsModalLabel" aria-hidden="true"  style="z-index:20000">
  <div class="modal-dialog modal-dialog-scrollable" role="document">
      <div class="modal-content">
          <div class="modal-header">
              <h5 class="modal-title" id="termsModalLabel">Terms and Conditions</h5>
              <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
              </button>
          </div>
          <div class="modal-body">
              <!-- Add your terms and conditions text here -->
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. ...
          </div>
          <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" id="cancelTermsBtn" >Cancel</button>
              <button type="button" class="btn btn-primary" id="acceptTermsBtn" data-bs-dismiss="modal">Accept</button>
          </div>
      </div>
  </div>
</div>

<script src="{% static 'user/js/register.js' %}"></script>
{% endblock %}

web/user/templates/user/template_reset_password.html
{% autoescape off %}
Hi {{ user.email }},

Please click on the link below to confirm your registration:

{{ protocol }}://{{ domain }}{% url 'user:password_reset_confirm' uidb64=uid token=token %}
{% endautoescape %}